import test from 'node:test';
import assert from 'node:assert/strict';
import { buildLeastPrivilegePlan } from '../src/live/plan.mjs';

const NOW = '2026-09-26T12:00:00.000Z';

test('filenames are derived from the timestamp, UTC', () => {
  const plan = buildLeastPrivilegePlan([], { now: NOW });
  assert.equal(plan.timestamp, '20260926120000');
  assert.equal(plan.filename, '20260926120000_least_privilege_grants.sql');
  assert.equal(plan.rollbackFilename, '20260926120000_least_privilege_grants_rollback.sql');
});

test('no findings -> a no-op migration and rollback, byte-exact', () => {
  const plan = buildLeastPrivilegePlan([], { now: NOW });
  assert.equal(
    plan.migrationSql,
    [
      '-- Least-privilege grants migration, generated by supabase-grants on 2026-09-26T12:00:00.000Z.',
      '-- Brings table GRANTs in line with what the RLS policies in this database actually allow.',
      '-- service_role is never touched. Roll back with the paired *_rollback.sql file.',
      '',
      '-- Nothing to do: every grant already matches a policy, and every policy has its grant.',
      '',
    ].join('\n')
  );
  assert.equal(
    plan.rollbackSql,
    [
      '-- Rollback for the least-privilege grants migration generated 2026-09-26T12:00:00.000Z.',
      '-- Restores exactly the privileges the migration removed/added; does not touch anything else.',
      '',
      '-- Nothing to roll back.',
      '',
    ].join('\n')
  );
});

test('grant_without_policy findings become grouped revoke statements, byte-exact', () => {
  const findings = [
    { kind: 'grant_without_policy', table: 'public.orders', role: 'anon', privilege: 'DELETE' },
    { kind: 'grant_without_policy', table: 'public.orders', role: 'anon', privilege: 'UPDATE' },
    { kind: 'grant_without_policy', table: 'public.orders', role: 'anon', privilege: 'DELETE' }, // duplicate, should dedupe
  ];
  const plan = buildLeastPrivilegePlan(findings, { now: NOW });
  assert.equal(
    plan.migrationSql,
    [
      '-- Least-privilege grants migration, generated by supabase-grants on 2026-09-26T12:00:00.000Z.',
      '-- Brings table GRANTs in line with what the RLS policies in this database actually allow.',
      '-- service_role is never touched. Roll back with the paired *_rollback.sql file.',
      '',
      '-- Privileges with no policy backing them (grant_without_policy).',
      'revoke update, delete on public.orders from anon;',
      '',
    ].join('\n')
  );
  assert.equal(
    plan.rollbackSql,
    [
      '-- Rollback for the least-privilege grants migration generated 2026-09-26T12:00:00.000Z.',
      '-- Restores exactly the privileges the migration removed/added; does not touch anything else.',
      '',
      '-- Restore what the migration revoked (grant_without_policy).',
      'grant update, delete on public.orders to anon;',
      '',
    ].join('\n')
  );
});

test('policy_without_grant findings become grouped grant statements', () => {
  const findings = [
    { kind: 'policy_without_grant', table: 'public.notes', role: 'authenticated', privilege: 'SELECT' },
    { kind: 'policy_without_grant', table: 'public.notes', role: 'authenticated', privilege: 'INSERT' },
  ];
  const plan = buildLeastPrivilegePlan(findings, { now: NOW });
  assert.match(plan.migrationSql, /grant select, insert on public\.notes to authenticated;/);
});

test('both kinds together produce both sections, in order', () => {
  const findings = [
    { kind: 'grant_without_policy', table: 'public.orders', role: 'anon', privilege: 'DELETE' },
    { kind: 'policy_without_grant', table: 'public.notes', role: 'authenticated', privilege: 'SELECT' },
  ];
  const plan = buildLeastPrivilegePlan(findings, { now: NOW });
  const revokeIdx = plan.migrationSql.indexOf('revoke delete on public.orders from anon;');
  const grantIdx = plan.migrationSql.indexOf('grant select on public.notes to authenticated;');
  assert.ok(revokeIdx > -1 && grantIdx > -1 && revokeIdx < grantIdx);
});

const LEGACY = [
  { kind: 'legacy_default_privileges', table: null, grantorRole: 'postgres', objectType: 'tables', grants: [{ grantee: 'anon', privileges: ['SELECT', 'INSERT'] }] },
  { kind: 'legacy_default_privileges', table: null, grantorRole: 'postgres', objectType: 'functions', grants: [{ grantee: 'authenticated', privileges: ['EXECUTE'] }] },
];

test('--pin-defaults revokes defaults for tables, sequences and functions for each grantor role, byte-exact with rollback', () => {
  const plan = buildLeastPrivilegePlan(LEGACY, { now: NOW, pinDefaults: true });
  assert.equal(
    plan.migrationSql,
    [
      '-- Least-privilege grants migration, generated by supabase-grants on 2026-09-26T12:00:00.000Z.',
      '-- Brings table GRANTs in line with what the RLS policies in this database actually allow.',
      '-- service_role is never touched. Roll back with the paired *_rollback.sql file.',
      '',
      "-- Stop depending on the platform's legacy default grants for tables, sequences and functions: the platform",
      '-- stops setting them for every project from 2026-10-30, so new objects should get explicit grants instead.',
      'alter default privileges for role postgres in schema public revoke all on tables from anon, authenticated;',
      'alter default privileges for role postgres in schema public revoke all on sequences from anon, authenticated;',
      'alter default privileges for role postgres in schema public revoke all on functions from anon, authenticated;',
      '',
    ].join('\n')
  );
  assert.equal(
    plan.rollbackSql,
    [
      '-- Rollback for the least-privilege grants migration generated 2026-09-26T12:00:00.000Z.',
      '-- Restores exactly the privileges the migration removed/added; does not touch anything else.',
      '',
      '-- Restore the legacy default privileges exactly as they were.',
      'alter default privileges for role postgres in schema public grant execute on functions to authenticated;',
      'alter default privileges for role postgres in schema public grant select, insert on tables to anon;',
      '',
    ].join('\n')
  );
});

test('--pin-defaults does nothing without the flag or without a legacy finding', () => {
  assert.doesNotMatch(buildLeastPrivilegePlan(LEGACY, { now: NOW, pinDefaults: false }).migrationSql, /alter default privileges/);
  assert.doesNotMatch(buildLeastPrivilegePlan([], { now: NOW, pinDefaults: true }).migrationSql, /alter default privileges/);
});

test('grant_dangerous_privilege findings are revoked, and restored by the rollback', () => {
  const findings = [
    { kind: 'grant_dangerous_privilege', table: 'public.orders', role: 'anon', privilege: 'TRIGGER' },
    { kind: 'grant_dangerous_privilege', table: 'public.orders', role: 'anon', privilege: 'TRUNCATE' },
  ];
  const plan = buildLeastPrivilegePlan(findings, { now: NOW });
  assert.match(plan.migrationSql, /^revoke truncate, trigger on public\.orders from anon;$/m);
  assert.match(plan.rollbackSql, /^grant truncate, trigger on public\.orders to anon;$/m);
});

test('granting a table with serial/identity columns also grants usage, select on its sequences', () => {
  const findings = [
    {
      kind: 'policy_without_grant', table: 'public.orders', role: 'authenticated', privilege: 'INSERT',
      sequences: [{ sequence: 'public.orders_id_seq', privileges: ['SELECT', 'USAGE'] }],
    },
    {
      kind: 'policy_without_grant', table: 'public.orders', role: 'authenticated', privilege: 'SELECT',
      sequences: [{ sequence: 'public.orders_id_seq', privileges: ['SELECT', 'USAGE'] }],
    },
  ];
  const plan = buildLeastPrivilegePlan(findings, { now: NOW });
  const seqLines = plan.migrationSql.split('\n').filter(l => l.includes('on sequence'));
  assert.deepEqual(seqLines, ['grant usage, select on sequence public.orders_id_seq to authenticated;']);
  assert.match(plan.rollbackSql, /^revoke usage, select on sequence public\.orders_id_seq from authenticated;$/m);
});

test('service_role never appears in an actual grant/revoke statement', () => {
  const findings = [
    { kind: 'grant_without_policy', table: 'public.orders', role: 'anon', privilege: 'DELETE' },
    { kind: 'policy_without_grant', table: 'public.notes', role: 'authenticated', privilege: 'SELECT' },
  ];
  const plan = buildLeastPrivilegePlan(findings, { now: NOW });
  const statementLines = (plan.migrationSql + plan.rollbackSql)
    .split('\n')
    .filter(line => /^(grant|revoke)\b/.test(line));
  assert.ok(statementLines.length > 0);
  for (const line of statementLines) assert.doesNotMatch(line, /service_role/);
});

test('info/other-kind findings (e.g. not_exposed) are ignored by the plan', () => {
  const findings = [{ kind: 'not_exposed', table: 'public.internal' }];
  const plan = buildLeastPrivilegePlan(findings, { now: NOW });
  assert.match(plan.migrationSql, /Nothing to do/);
});

// --- second review round ----------------------------------------------------

test('--pin-defaults only emits statements for postgres; other grantors get a comment, not a statement', () => {
  const findings = [
    ...LEGACY,
    { kind: 'legacy_default_privileges', table: null, grantorRole: 'supabase_admin', objectType: 'tables', grants: [{ grantee: 'anon', privileges: ['SELECT'] }] },
  ];
  const plan = buildLeastPrivilegePlan(findings, { now: NOW, pinDefaults: true });
  const statements = plan.migrationSql.split('\n').filter(l => l.startsWith('alter default privileges'));
  assert.equal(statements.length, 3);
  assert.ok(statements.every(l => l.startsWith('alter default privileges for role postgres in schema public revoke all on ')));
  assert.match(plan.migrationSql, /-- Legacy default privileges also exist for supabase_admin/);
  assert.doesNotMatch(plan.rollbackSql, /supabase_admin/);
});

test('the plan never revokes SELECT from a role with a write policy on that table', () => {
  const findings = [
    { kind: 'grant_without_policy', table: 'public.orders', role: 'authenticated', privilege: 'SELECT' },
    { kind: 'grant_without_policy', table: 'public.orders', role: 'authenticated', privilege: 'DELETE' },
    { kind: 'write_without_select_policy', table: 'public.orders', role: 'authenticated' },
  ];
  const plan = buildLeastPrivilegePlan(findings, { now: NOW });
  assert.match(plan.migrationSql, /^revoke delete on public\.orders from authenticated;$/m);
  assert.doesNotMatch(plan.migrationSql, /revoke[^;]*select[^;]*from authenticated/);
});
