// Turns live/analyze.mjs findings into a least-privilege migration: a
// `revoke` for every grant_without_policy / grant_dangerous_privilege, a
// `grant` for every policy_without_grant (plus usage/select on the sequences
// behind that table's serial/identity columns). Pure string building — never
// touches a database. service_role is never touched.

function tsForFilename(date) {
  const pad = n => String(n).padStart(2, '0');
  return (
    `${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}` +
    `${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}`
  );
}

function quoteIdent(name) {
  return /^[a-z_][a-z0-9_]*$/.test(name) ? name : `"${name.replace(/"/g, '""')}"`;
}

const TABLE_PRIV_ORDER = ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'REFERENCES', 'TRIGGER', 'MAINTAIN'];
const SEQUENCE_PRIV_ORDER = ['USAGE', 'SELECT', 'UPDATE'];
const DEFAULT_ACL_PRIV_ORDER = [...TABLE_PRIV_ORDER, 'USAGE', 'EXECUTE'];

function privList(privileges, order) {
  return [...new Set(privileges)]
    .sort((a, b) => order.indexOf(a) - order.indexOf(b))
    .map(p => p.toLowerCase())
    .join(', ');
}

// Groups {target, role, privileges[]} into one entry per target+role.
function groupByTargetRole(items) {
  const grouped = new Map();
  for (const { target, role, privileges } of items) {
    const key = `${target}\u0000${role}`;
    if (!grouped.has(key)) grouped.set(key, { target, role, privileges: [] });
    grouped.get(key).privileges.push(...privileges);
  }
  return [...grouped.values()].sort((a, b) => a.target.localeCompare(b.target) || a.role.localeCompare(b.role));
}

function tableItems(findings, kind) {
  return groupByTargetRole(
    findings.filter(f => f.kind === kind).map(f => ({ target: f.table, role: f.role, privileges: [f.privilege] }))
  );
}

// Never revoke SELECT from a role that has write policies on the table:
// UPDATE/DELETE only reach rows the role can select.
function withoutSelectForWriters(findings, revokeFindings) {
  const writers = new Set(
    findings.filter(f => f.kind === 'write_without_select_policy').map(f => `${f.table}\u0000${f.role}`)
  );
  return revokeFindings.filter(f => !(f.privilege === 'SELECT' && writers.has(`${f.table}\u0000${f.role}`)));
}

// Migrations run as `postgres`, so that's the only grantor whose defaults a
// migration can change; supabase_admin's defaults apply to platform-created
// objects.
const MIGRATION_ROLE = 'postgres';

function sequenceItems(findings) {
  return groupByTargetRole(
    findings
      .filter(f => f.kind === 'policy_without_grant')
      .flatMap(f => (f.sequences || []).map(s => ({ target: s.sequence, role: f.role, privileges: s.privileges })))
  );
}

function tableStatements(verb, prep, groups) {
  return groups.map(g => `${verb} ${privList(g.privileges, TABLE_PRIV_ORDER)} on ${g.target} ${prep} ${g.role};`);
}

function sequenceStatements(verb, prep, groups) {
  return groups.map(g => `${verb} ${privList(g.privileges, SEQUENCE_PRIV_ORDER)} on sequence ${g.target} ${prep} ${g.role};`);
}

// findings: the array from live/analyze.mjs's analyzeLive().
// opts.pinDefaults: when the project still has legacy default privileges,
//   revoke them for tables, sequences and functions (all three kinds the
//   2026-10-30 change covers) so the project stops depending on them.
// opts.now: Date, for deterministic filenames/headers in tests.
export function buildLeastPrivilegePlan(findings, opts = {}) {
  const now = opts.now ? new Date(opts.now) : new Date();
  const timestamp = tsForFilename(now);

  const toRevoke = tableItems(withoutSelectForWriters(findings, findings), 'grant_without_policy');
  const dangerous = tableItems(findings, 'grant_dangerous_privilege');
  const toGrant = tableItems(findings, 'policy_without_grant');
  const sequencesToGrant = sequenceItems(findings);
  const allLegacy = opts.pinDefaults ? findings.filter(f => f.kind === 'legacy_default_privileges') : [];
  const legacyDefaults = allLegacy.filter(f => f.grantorRole === MIGRATION_ROLE);
  const otherGrantors = [...new Set(allLegacy.filter(f => f.grantorRole !== MIGRATION_ROLE).map(f => f.grantorRole))].sort();
  const grantorRoles = legacyDefaults.length ? [MIGRATION_ROLE] : [];

  const migrationLines = [
    `-- Least-privilege grants migration, generated by supabase-grants on ${now.toISOString()}.`,
    `-- Brings table GRANTs in line with what the RLS policies in this database actually allow.`,
    `-- service_role is never touched. Roll back with the paired *_rollback.sql file.`,
    '',
  ];
  const rollbackLines = [
    `-- Rollback for the least-privilege grants migration generated ${now.toISOString()}.`,
    `-- Restores exactly the privileges the migration removed/added; does not touch anything else.`,
    '',
  ];

  const nothingToDo = !toRevoke.length && !dangerous.length && !toGrant.length && !grantorRoles.length;
  if (nothingToDo) {
    migrationLines.push('-- Nothing to do: every grant already matches a policy, and every policy has its grant.');
    rollbackLines.push('-- Nothing to roll back.');
  }

  if (toRevoke.length) {
    migrationLines.push('-- Privileges with no policy backing them (grant_without_policy).');
    migrationLines.push(...tableStatements('revoke', 'from', toRevoke), '');
    rollbackLines.push('-- Restore what the migration revoked (grant_without_policy).');
    rollbackLines.push(...tableStatements('grant', 'to', toRevoke), '');
  }
  if (dangerous.length) {
    migrationLines.push('-- Privileges the Data API never needs; TRUNCATE is not subject to RLS (grant_dangerous_privilege).');
    migrationLines.push(...tableStatements('revoke', 'from', dangerous), '');
    rollbackLines.push('-- Restore what the migration revoked (grant_dangerous_privilege).');
    rollbackLines.push(...tableStatements('grant', 'to', dangerous), '');
  }
  if (toGrant.length) {
    migrationLines.push('-- Policies with no privilege to run under (policy_without_grant).');
    migrationLines.push(...tableStatements('grant', 'to', toGrant), '');
    rollbackLines.push('-- Undo what the migration granted.');
    rollbackLines.push(...tableStatements('revoke', 'from', toGrant), '');
  }
  if (sequencesToGrant.length) {
    migrationLines.push('-- Sequences behind serial/identity columns of the tables granted above.');
    migrationLines.push(...sequenceStatements('grant', 'to', sequencesToGrant), '');
    rollbackLines.push('-- Undo the sequence grants.');
    rollbackLines.push(...sequenceStatements('revoke', 'from', sequencesToGrant), '');
  }
  if (grantorRoles.length) {
    migrationLines.push(
      "-- Stop depending on the platform's legacy default grants for tables, sequences and functions: the platform",
      '-- stops setting them for every project from 2026-10-30, so new objects should get explicit grants instead.'
    );
    for (const role of grantorRoles) {
      for (const kind of ['tables', 'sequences', 'functions']) {
        migrationLines.push(
          `alter default privileges for role ${quoteIdent(role)} in schema public revoke all on ${kind} from anon, authenticated;`
        );
      }
    }
    migrationLines.push('');

    rollbackLines.push('-- Restore the legacy default privileges exactly as they were.');
    for (const f of [...legacyDefaults].sort((a, b) => a.grantorRole.localeCompare(b.grantorRole) || a.objectType.localeCompare(b.objectType))) {
      for (const g of f.grants) {
        rollbackLines.push(
          `alter default privileges for role ${quoteIdent(f.grantorRole)} in schema public grant ${privList(g.privileges, DEFAULT_ACL_PRIV_ORDER)} on ${f.objectType} to ${g.grantee};`
        );
      }
    }
    rollbackLines.push('');
  }
  if (otherGrantors.length) {
    migrationLines.push(
      `-- Legacy default privileges also exist for ${otherGrantors.join(', ')}. Those apply to objects that role creates`,
      '-- (platform-managed), and a migration running as postgres cannot change them; left as they are.',
      ''
    );
  }

  return {
    timestamp,
    filename: `${timestamp}_least_privilege_grants.sql`,
    rollbackFilename: `${timestamp}_least_privilege_grants_rollback.sql`,
    migrationSql: migrationLines.join('\n').trimEnd() + '\n',
    rollbackSql: rollbackLines.join('\n').trimEnd() + '\n',
  };
}
